"""add courage_image_url to outfits

Revision ID: 37168f27136b
Revises: da09de1d5720
Create Date: 2026-06-14 13:49:08.591888

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37168f27136b"
down_revision: Union[str, Sequence[str], None] = "da09de1d5720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outfits", sa.Column("courage_image_url", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outfits", "courage_image_url")
    # ### end Alembic commands ###
