"""add secondary_region_code to users

Revision ID: da09de1d5720
Revises: 3cc49142ccf6
Create Date: 2026-06-12 14:48:15.675003

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da09de1d5720"
down_revision: Union[str, Sequence[str], None] = "3cc49142ccf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("secondary_region_code", sa.String(length=5), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "secondary_region_code")
    # ### end Alembic commands ###
